blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://github.com/XilinJia/VoiVista/discussions/new?category=questions
    about: Ask about anything VoiVista-related
  - name: ğŸ’¬ IRC
    url: https://web.libera.chat/#voivista
    about: Chat with us via IRC for quick Q/A
  - name: ğŸ’¬ Matrix
    url: https://matrix.to/#/#voivista:libera.chat
    about: Chat with us via Matrix for quick Q/A
